version: '3.7'

services:
  songbot:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - TG_TOKEN
    ports:
      - 80:8080

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - /songbot/mysql:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080